#...
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-boot-app
  labels:
    app: sprint-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sprint-boot-app
  template:
    metadata:
      labels:
        app: sprint-boot-app
    spec:
      containers:
      - name: sprint-boot-app
<<<<<<< HEAD
        image: danielmelo5627/ultimate-cicd
=======
        image: camilacarolina/ultimate-cicd:13
>>>>>>> 31004f1b744895dabd8f1c50be3139532dd99147
        ports:
        - containerPort: 8080

